/* Auto-generated by learn/residual.py — do not edit by hand. */
#ifndef LEARNED_MODEL_H
#define LEARNED_MODEL_H

#define LEARNED_N_FEATURES 9
#define LEARNED_EPS 0.05f

static const float learned_beta[LEARNED_N_FEATURES] = {
    0.00471523956f,  /* bias */
    0.0144385428f,  /* tanh(w/eps) */
    -0.00330314361f,  /* w */
    0.00320334937f,  /* sin6t */
    -0.0103436464f,  /* cos6t */
    0.000732912291f,  /* sin12t */
    0.00251634496f,  /* cos12t */
    -0.00177679155f,  /* u */
    -0.00920115212f  /* u*sin6t */
};

/* Learned disturbance torque: d_hat(theta_m, omega_m, u). */
static inline float learned_disturbance(float theta_m, float omega_m, float u) {
    const float e = LEARNED_EPS;
    const float s6 = sinf(6.0f * theta_m), c6 = cosf(6.0f * theta_m);
    const float s12 = sinf(12.0f * theta_m), c12 = cosf(12.0f * theta_m);
    const float phi[LEARNED_N_FEATURES] = {
        1.0f, tanhf(omega_m / e), omega_m, s6, c6, s12, c12, u, u * s6};
    float acc = 0.0f;
    for (int i = 0; i < LEARNED_N_FEATURES; i++) acc += learned_beta[i] * phi[i];
    return acc;
}

/* Friction component (for the momentum observer). */
static inline float learned_friction(float omega_m) {
    return learned_beta[0] + learned_beta[1] * tanhf(omega_m / LEARNED_EPS)
           + learned_beta[2] * omega_m;
}

#endif /* LEARNED_MODEL_H */
