"""Learned disturbance model for the SEA (friction + cogging + ripple).

The linear MPC prediction model treats the motor as ideal: tau_m = Kt * u.
In reality, friction, cogging, and torque ripple steal torque from the
motor.  We learn a static disturbance map from *closed-loop* data:

    d(x, u) = Kt*u_applied - Jm*omega_m_dot - bm*omega_m - tau_s_hat

i.e. the torque that the motor puts into the spring, minus what the linear
model (with identified Jm, bm) expects.  The basis captures:

    [1, tanh(omega_m/eps), omega_m]        -> Coulomb + viscous friction
    [sin(6 theta_m), cos(6 theta_m), ...]  -> cogging harmonics
    [u * sin(6 theta_m)]                   -> current-proportional ripple

The fitted map is embedded in the control loop in two places:

  * as a **feedforward** current compensation u_ff = d_hat(x,u)/Kt — instant
    disturbance rejection (the MPC has no integral action);
  * as the **friction estimate** for the momentum observer, sharpening
    collision detection.

Ridge regression keeps the model deployable: on the STM32 it is a dot
product (`learned_model.h`, generated by export_to_c()).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class ResidualConfig:
    ridge: float = 1e-3     # L2 regularization
    eps: float = 0.05       # friction smoothing velocity [rad/s]
    u_ff_max: float = 1.0   # clamp on feedforward current [A]


def basis(theta_m: np.ndarray, omega_m: np.ndarray, u: np.ndarray,
          eps: float = 0.05) -> np.ndarray:
    """Feature matrix for the disturbance model."""
    t = theta_m
    return np.column_stack([
        np.ones_like(t),
        np.tanh(omega_m / eps), omega_m,
        np.sin(6 * t), np.cos(6 * t),
        np.sin(12 * t), np.cos(12 * t),
        u, u * np.sin(6 * t),
    ])


FEATURE_NAMES = ["bias", "tanh(w/eps)", "w", "sin6t", "cos6t",
                 "sin12t", "cos12t", "u", "u*sin6t"]


class LearnedDisturbance:
    """Learned motor-side disturbance model (friction + cogging + ripple)."""

    def __init__(self, cfg: ResidualConfig | None = None):
        self.cfg = cfg if cfg is not None else ResidualConfig()
        self.beta = None
        self.n_features = None

    def fit(self, theta_m: np.ndarray, omega_m: np.ndarray, u: np.ndarray,
            d: np.ndarray) -> dict:
        """Fit d as a function of (theta_m, omega_m, u) via ridge regression."""
        X = basis(theta_m, omega_m, u, self.cfg.eps)
        self.n_features = X.shape[1]
        A = np.vstack([X, np.sqrt(self.cfg.ridge) * np.eye(self.n_features)])
        b = np.concatenate([d, np.zeros(self.n_features)])
        self.beta, *_ = np.linalg.lstsq(A, b, rcond=None)
        d_hat = self.predict(theta_m, omega_m, u)
        ss_res = float(np.sum((d - d_hat) ** 2))
        ss_tot = float(np.sum((d - np.mean(d)) ** 2))
        return {"r2": 1.0 - ss_res / ss_tot if ss_tot > 0 else 1.0,
                "beta": self.beta.copy()}

    def predict(self, theta_m: np.ndarray, omega_m: np.ndarray,
                u: np.ndarray) -> np.ndarray:
        return basis(theta_m, omega_m, u, self.cfg.eps) @ self.beta

    def friction_only(self, omega_m: float) -> float:
        """Friction component used by the momentum observer [N.m]."""
        b = self.beta
        eps = self.cfg.eps
        return float(b[0] + b[1] * np.tanh(omega_m / eps) + b[2] * omega_m)

    def feedforward(self, theta_m: float, omega_m: float, u: float,
                    Kt: float) -> float:
        """Feedforward current compensation u_ff = d_hat / Kt [A]."""
        d_hat = float(self.predict(np.array([theta_m]), np.array([omega_m]),
                                   np.array([u]))[0])
        u_ff = d_hat / Kt
        return float(np.clip(u_ff, -self.cfg.u_ff_max, self.cfg.u_ff_max))

    def export_to_c(self, path: str) -> str:
        """Write firmware header `learned_model.h` with the fitted model."""
        lines = [
            "/* Auto-generated by learn/residual.py — do not edit by hand. */",
            "#ifndef LEARNED_MODEL_H",
            "#define LEARNED_MODEL_H",
            "",
            f"#define LEARNED_N_FEATURES {self.n_features}",
            f"#define LEARNED_EPS {self.cfg.eps:.9g}f",
            "",
            "static const float learned_beta[LEARNED_N_FEATURES] = {",
        ]
        for i, (name, b) in enumerate(zip(FEATURE_NAMES, self.beta)):
            comma = "," if i < self.n_features - 1 else ""
            lines.append(f"    {b:.9g}f{comma}  /* {name} */")
        lines += [
            "};",
            "",
            "/* Learned disturbance torque: d_hat(theta_m, omega_m, u). */",
            "static inline float learned_disturbance(float theta_m, float omega_m, float u) {",
            "    const float e = LEARNED_EPS;",
            "    const float s6 = sinf(6.0f * theta_m), c6 = cosf(6.0f * theta_m);",
            "    const float s12 = sinf(12.0f * theta_m), c12 = cosf(12.0f * theta_m);",
            "    const float phi[LEARNED_N_FEATURES] = {",
            "        1.0f, tanhf(omega_m / e), omega_m, s6, c6, s12, c12, u, u * s6};",
            "    float acc = 0.0f;",
            "    for (int i = 0; i < LEARNED_N_FEATURES; i++) acc += learned_beta[i] * phi[i];",
            "    return acc;",
            "}",
            "",
            "/* Friction component (for the momentum observer). */",
            "static inline float learned_friction(float omega_m) {",
            "    return learned_beta[0] + learned_beta[1] * tanhf(omega_m / LEARNED_EPS)",
            "           + learned_beta[2] * omega_m;",
            "}",
            "",
            "#endif /* LEARNED_MODEL_H */",
        ]
        text = "\n".join(lines) + "\n"
        with open(path, "w") as f:
            f.write(text)
        return "learned_model.h"
