"""Learned disturbance model for the SEA (friction + cogging + ripple).

The linear MPC prediction model treats the motor as ideal: tau_m = Kt * u.
In reality, friction, cogging, and torque ripple steal torque from the
motor.  We learn a static disturbance map from *closed-loop* data:

    d(x, u) = Kt*u_applied - Jm*omega_m_dot - bm*omega_m - tau_s_hat

i.e. the torque that the motor puts into the spring, minus what the linear
model (with identified Jm, bm) expects.  The basis captures:

    [1, tanh(omega_m/eps), omega_m]        -> Coulomb + viscous friction
    [sin(6 theta_m), cos(6 theta_m), ...]  -> cogging harmonics
    [u * sin(6 theta_m)]                   -> current-proportional ripple
    [omega_m(k-1..k-lag), u(k-1..k-lag)]   -> dynamic features (lagged)

The **lagged** features matter on real hardware: the motor-side residual
also contains short-transient terms that a purely static map cannot see —
current-loop lag (L/R comparable to the torque-loop period) and the
identified-inertia error leaking in through -Jm_hat * omega_dot.  Because
omega_dot ~ (omega_k - omega_k-1)/T, lagged omega (and lagged u for the
current transient) make those components representable.  Without them the
map generalizes poorly (held-out R² ≈ 0) and the feedforward can
*destabilize* edge-rich tracking (measured on the GM5208 sim, Aug 2026).

The fitted model is embedded in the control loop in two places:

  * as a **feedforward** current compensation u_ff = d_hat(x,u)/Kt — instant
    disturbance rejection (the MPC has no integral action);
  * as the **friction estimate** for the momentum observer, sharpening
    collision detection.

Ridge regression keeps the model deployable: on the STM32 it is a dot
product (`learned_model.h`, generated by export_to_c()).  The lagged
features need the firmware to hold the previous `lag` commands and
velocities (see the generated header's signature and `tasks.c`).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class ResidualConfig:
    ridge: float = 1e-3     # L2 regularization
    eps: float = 0.05       # friction smoothing velocity [rad/s]
    u_ff_max: float = 1.0   # clamp on feedforward current [A]
    lag: int = 2            # dynamic features: lag steps of omega_m and u


def _lagged(x, lag: int) -> list[np.ndarray]:
    """Return [x_{k-1}, ..., x_{k-lag}], zero-padded at the trajectory start."""
    x = np.asarray(x, dtype=float)
    return [np.concatenate([np.zeros(min(i, len(x))), x[:max(0, len(x) - i)]])
            for i in range(1, lag + 1)]


def basis(theta_m: np.ndarray, omega_m: np.ndarray, u: np.ndarray,
          eps: float = 0.05,
          u_lags: list[np.ndarray] | None = None,
          w_lags: list[np.ndarray] | None = None) -> np.ndarray:
    """Feature matrix for the disturbance model.

    Column order: static (state + command) first, then lagged omega, then
    lagged u.  `u_lags` / `w_lags` are the lagged series (see `_lagged`);
    when omitted the basis is the classic static map.
    """
    t = theta_m
    cols = [
        np.ones_like(t),
        np.tanh(omega_m / eps), omega_m,
        np.sin(6 * t), np.cos(6 * t),
        np.sin(12 * t), np.cos(12 * t),
        u, u * np.sin(6 * t),
    ]
    if w_lags is not None:
        cols += list(w_lags)
    if u_lags is not None:
        cols += list(u_lags)
    return np.column_stack(cols)


FEATURE_NAMES = ["bias", "tanh(w/eps)", "w", "sin6t", "cos6t",
                 "sin12t", "cos12t", "u", "u*sin6t"]


def feature_names(lag: int) -> list[str]:
    """Full feature names matching `basis` column order for a given lag."""
    return (list(FEATURE_NAMES)
            + [f"w_lag{i}" for i in range(1, lag + 1)]
            + [f"u_lag{i}" for i in range(1, lag + 1)])


class LearnedDisturbance:
    """Learned motor-side disturbance model (friction + cogging + ripple)."""

    def __init__(self, cfg: ResidualConfig | None = None, kt: float = 0.1):
        self.cfg = cfg if cfg is not None else ResidualConfig()
        self.kt = kt                    # torque constant for u_ff = d_hat/Kt
        self.beta = None                # full model (feedforward)
        self.friction_beta = None       # dedicated 3-feature friction model
        self.n_features = None
        self.reset()

    def reset(self) -> None:
        """Clear the command/velocity history (call at each run start)."""
        self._w_hist = [0.0] * self.cfg.lag   # [w_{k-1}, w_{k-2}, ...]
        self._u_hist = [0.0] * self.cfg.lag   # [u_{k-1}, u_{k-2}, ...]

    def fit(self, theta_m: np.ndarray, omega_m: np.ndarray, u: np.ndarray,
            d: np.ndarray) -> dict:
        """Fit d as a function of (theta_m, omega_m, u) via ridge regression."""
        X = basis(theta_m, omega_m, u, self.cfg.eps,
                  u_lags=_lagged(u, self.cfg.lag),
                  w_lags=_lagged(omega_m, self.cfg.lag))
        self.n_features = X.shape[1]
        A = np.vstack([X, np.sqrt(self.cfg.ridge) * np.eye(self.n_features)])
        b = np.concatenate([d, np.zeros(self.n_features)])
        self.beta, *_ = np.linalg.lstsq(A, b, rcond=None)
        d_hat = self.predict(theta_m, omega_m, u)
        ss_res = float(np.sum((d - d_hat) ** 2))
        ss_tot = float(np.sum((d - np.mean(d)) ** 2))
        # Dedicated friction model for the momentum observer.  The lagged
        # command features are collinear with the bias in quasi-steady data,
        # so the full model's beta[0..2] no longer isolate friction (the fit
        # spreads the constant across bias/u/lags — measured bias -0.15 vs
        # true Coulomb +0.008).  Refit [1, tanh(w/eps), w] alone so the
        # observer keeps a physically meaningful estimate; the FF still uses
        # the full beta.
        Xf = np.column_stack([np.ones_like(omega_m),
                              np.tanh(omega_m / self.cfg.eps), omega_m])
        Af = np.vstack([Xf, np.sqrt(self.cfg.ridge) * np.eye(3)])
        bf = np.concatenate([d, np.zeros(3)])
        self.friction_beta, *_ = np.linalg.lstsq(Af, bf, rcond=None)
        return {"r2": 1.0 - ss_res / ss_tot if ss_tot > 0 else 1.0,
                "beta": self.beta.copy()}

    def predict(self, theta_m: np.ndarray, omega_m: np.ndarray,
                u: np.ndarray,
                u_lags: list[np.ndarray] | None = None,
                w_lags: list[np.ndarray] | None = None) -> np.ndarray:
        if u_lags is None:
            u_lags = _lagged(u, self.cfg.lag)
        if w_lags is None:
            w_lags = _lagged(omega_m, self.cfg.lag)
        return basis(theta_m, omega_m, u, self.cfg.eps,
                     u_lags=u_lags, w_lags=w_lags) @ self.beta

    def friction_only(self, omega_m: float) -> float:
        """Friction component used by the momentum observer [N.m].

        Uses the dedicated 3-feature fit (see fit()): the full model's
        first coefficients are contaminated by bias/u collinearity.
        """
        b = self.friction_beta
        eps = self.cfg.eps
        return float(b[0] + b[1] * np.tanh(omega_m / eps) + b[2] * omega_m)

    def feedforward(self, theta_m: float, omega_m: float, u: float,
                    Kt: float) -> float:
        """Feedforward current compensation u_ff = d_hat / Kt [A].

        Stateful: uses the stored command/velocity history for the lagged
        features, then shifts the history with the current (u, omega).
        """
        eps = self.cfg.eps
        t = theta_m
        phi = np.array([
            1.0,
            np.tanh(omega_m / eps), omega_m,
            np.sin(6 * t), np.cos(6 * t),
            np.sin(12 * t), np.cos(12 * t),
            u, u * np.sin(6 * t),
            *self._w_hist,   # w_{k-1} .. w_{k-lag}
            *self._u_hist,   # u_{k-1} .. u_{k-lag}
        ])
        d_hat = float(phi @ self.beta)
        # shift history (most recent first)
        if self.cfg.lag:
            self._w_hist = [omega_m] + self._w_hist[:-1]
            self._u_hist = [u] + self._u_hist[:-1]
        u_ff = d_hat / Kt
        return float(np.clip(u_ff, -self.cfg.u_ff_max, self.cfg.u_ff_max))

    def export_to_c(self, path: str) -> str:
        """Write firmware header `learned_model.h` with the fitted model."""
        from model.c_export import c_float

        lag = self.cfg.lag
        names = feature_names(lag)
        # signature: current state + command, then lagged w, then lagged u
        sig_args = (", ".join(["float theta_m", "float omega_m", "float u"]
                              + [f"float w_prev{i}" for i in range(1, lag + 1)]
                              + [f"float u_prev{i}" for i in range(1, lag + 1)]))
        phi_entries = (["1.0f", "tanhf(omega_m / e)", "omega_m",
                        "s6", "c6", "s12", "c12", "u", "u * s6"]
                       + [f"w_prev{i}" for i in range(1, lag + 1)]
                       + [f"u_prev{i}" for i in range(1, lag + 1)])
        lines = [
            "/* Auto-generated by learn/residual.py — do not edit by hand. */",
            "#ifndef LEARNED_MODEL_H",
            "#define LEARNED_MODEL_H",
            "#include <math.h>",
            "",
            f"#define LEARNED_N_FEATURES {self.n_features}",
            f"#define LEARNED_EPS {c_float(self.cfg.eps)}",
            f"#define LEARNED_LAG {lag}",
            "",
            "static const float learned_beta[LEARNED_N_FEATURES] = {",
        ]
        for i, (name, b) in enumerate(zip(names, self.beta)):
            comma = "," if i < self.n_features - 1 else ""
            lines.append(f"    {c_float(b)}{comma}  /* {name} */")
        lines += [
            "};",
            "",
            "/* Dedicated friction model for the momentum observer (fitted on",
            " * [1, tanh(w/eps), w] — see learn/residual.py fit()). */",
            "static const float learned_fric_beta[3] = {",
            f"    {c_float(self.friction_beta[0])},  /* bias */",
            f"    {c_float(self.friction_beta[1])},  /* tanh(w/eps) */",
            f"    {c_float(self.friction_beta[2])}   /* w */",
            "};",
            "",
            f"#define LEARNED_KT {c_float(self.kt)}",
            f"#define LEARNED_U_FF_MAX {c_float(self.cfg.u_ff_max)}",
            "",
            "/* Learned disturbance torque: d_hat(theta_m, omega_m, u, history). */",
            f"static inline float learned_disturbance({sig_args}) {{",
            "    const float e = LEARNED_EPS;",
            "    const float s6 = sinf(6.0f * theta_m), c6 = cosf(6.0f * theta_m);",
            "    const float s12 = sinf(12.0f * theta_m), c12 = cosf(12.0f * theta_m);",
            f"    const float phi[LEARNED_N_FEATURES] = {{{', '.join(phi_entries)}}};",
            "    float acc = 0.0f;",
            "    for (int i = 0; i < LEARNED_N_FEATURES; i++) acc += learned_beta[i] * phi[i];",
            "    return acc;",
            "}",
            "",
            "/* Feedforward current compensation: u_ff = d_hat / Kt, clamped to",
            " * +-LEARNED_U_FF_MAX A — mirrors the Python feedforward().",
            " * The caller (tasks.c) must keep the previous `lag` commands and",
            " * velocities and pass them as w_prev1.. / u_prev1.. (newest first). */",
            f"static inline float learned_feedforward({sig_args}) {{",
            f"    float u_ff = learned_disturbance(theta_m, omega_m, u"
            + "".join(f", w_prev{i}" for i in range(1, lag + 1))
            + "".join(f", u_prev{i}" for i in range(1, lag + 1))
            + ") / LEARNED_KT;",
            "    if (u_ff > LEARNED_U_FF_MAX) return LEARNED_U_FF_MAX;",
            "    if (u_ff < -LEARNED_U_FF_MAX) return -LEARNED_U_FF_MAX;",
            "    return u_ff;",
            "}",
            "",
            "/* Friction component (for the momentum observer) — uses the",
            " * dedicated friction fit, not the full-model coefficients. */",
            "static inline float learned_friction(float omega_m) {",
            "    return learned_fric_beta[0] + learned_fric_beta[1] * tanhf(omega_m / LEARNED_EPS)",
            "           + learned_fric_beta[2] * omega_m;",
            "}",
            "",
            "#endif /* LEARNED_MODEL_H */",
        ]
        text = "\n".join(lines) + "\n"
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        return "learned_model.h"
