/**
 * sea-mpc firmware — main skeleton (STM32G431CB on the B-G431B-ESC1).
 *
 * Generated with CubeMX for clocks/peripherals; the control code lives in
 * foc.c / encoder.c / sea_observer.c / mpc.c / admm.c / impedance.c /
 * safety.c / tasks.c.  This file only wires them together.
 *
 * ISR wiring (see tasks.c):
 *   TIM2 10 kHz  -> current_loop_isr()   (FOC + current PI)
 *   TIM3  2 kHz  -> torque_loop_isr()    (observer + MPC + FF + safety)
 * FreeRTOS       -> telemetry_task()     (USB-CDC logging, 1 kHz)
 */

#include "main.h"
#include "tasks.h"

/* generated model headers live in Core/Inc (copied from results/) */
#include "learned_model.h"
#include "mpc_model.h"

static void MX_GPIO_Init(void);
static void MX_TIM1_Init(void);
static void MX_TIM2_Init(void);
static void MX_TIM3_Init(void);
static void MX_SPI1_Init(void);
static void MX_SPI2_Init(void);
static void MX_ADC1_Init(void);

volatile uint8_t g_imp_active = 1;

int main(void) {
    HAL_Init();
    SystemClock_Config();        /* 170 MHz, see CubeMX .ioc */

    MX_GPIO_Init();
    MX_TIM1_Init();              /* 3-phase PWM (100 kHz) + dead-time */
    MX_TIM2_Init();              /* current-loop tick (10 kHz)        */
    MX_TIM3_Init();              /* torque-loop tick (2 kHz)          */
    MX_SPI1_Init();              /* motor encoder                     */
    MX_SPI2_Init();              /* output encoder                    */
    MX_ADC1_Init();              /* phase currents                    */

    control_init();              /* build the control stack           */

    MX_FREERTOS_Init();          /* create telemetry_task             */

    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_2);
    HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_3);
    HAL_TIM_Base_Start_IT(&htim2);
    HAL_TIM_Base_Start_IT(&htim3);

    osKernelStart();
    for (;;) { }
}

/* --- TIM2 (10 kHz): current loop --------------------------------------- */
void TIM2_IRQHandler(void) {
    HAL_TIM_IRQHandler(&htim2);
    current_loop_isr();
}

/* --- TIM3 (2 kHz): torque loop ------------------------------------------ */
void TIM3_IRQHandler(void) {
    HAL_TIM_IRQHandler(&htim3);
    torque_loop_isr();
}

/* --- platform glue used by tasks.c -------------------------------------- */

float adc_phase_a(void) {
    /* read one phase current via ADC1 (two-shunt or integrated sense) */
    HAL_ADC_Start(&hadc1);
    if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK)
        return (float)HAL_ADC_GetValue(&hadc1) * 0.001f; /* scale to A */
    return 0.0f;
}

float adc_phase_b(void) {
    return 0.0f;   /* placeholder: second phase or reconstruct from i_a+i_b */
}

uint16_t spi1_read_word(uint8_t reg) {
    uint8_t tx[2] = { (uint8_t)(0x40 | (reg >> 6)), (uint8_t)(reg << 2) };
    uint8_t rx[2] = { 0, 0 };
    HAL_GPIO_WritePin(ENC1_CS_GPIO_Port, ENC1_CS_Pin, GPIO_PIN_RESET);
    HAL_SPI_TransmitReceive(&hspi1, tx, rx, 2, 10);
    HAL_GPIO_WritePin(ENC1_CS_GPIO_Port, ENC1_CS_Pin, GPIO_PIN_SET);
    return (uint16_t)((rx[0] << 8) | rx[1]);
}

uint16_t spi2_read_word(uint8_t reg) {
    uint8_t tx[2] = { (uint8_t)(0x40 | (reg >> 6)), (uint8_t)(reg << 2) };
    uint8_t rx[2] = { 0, 0 };
    HAL_GPIO_WritePin(ENC2_CS_GPIO_Port, ENC2_CS_Pin, GPIO_PIN_RESET);
    HAL_SPI_TransmitReceive(&hspi2, tx, rx, 2, 10);
    HAL_GPIO_WritePin(ENC2_CS_GPIO_Port, ENC2_CS_Pin, GPIO_PIN_SET);
    return (uint16_t)((rx[0] << 8) | rx[1]);
}

void pwm_update(void *foc) {
    /* copy foc->duty[] into TIM1 CCR registers (with dead time inserted
     * by the timer).  See foc.h for the duty layout. */
    (void)foc;
}

void cdc_send(const char *s, int len) {
    extern UART_HandleTypeDef huart2;   /* or USB CDC handle */
    HAL_UART_Transmit(&huart2, (uint8_t *)s, len, 100);
}

void osDelay(uint32_t ms) { (void)ms; }   /* provided by CMSIS-RTOS in real build */
uint32_t osKernelGetTickCount(void) { return 0; }

void start_timers(void) { /* TIMs already started in main */ }

void SystemClock_Config(void) { /* generated by CubeMX */ }
void MX_FREERTOS_Init(void) { /* generated by CubeMX: telemetry_task */ }
